stages:
- test
- deploy

include:
  - project: 'CordialExperiences/apps/app-gitlab-snippets'
    ref: master
    file: '.helm-dev-setup.yml'

services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://localhost:2375"

helmunit:
  stage: test
  image: 960048260646.dkr.ecr.us-west-2.amazonaws.com/helm-tester:latest
  script:
    - helm template nodelocal-dns-cache | kubeval -v 1.14.6 --strict

helmpush:
  stage: deploy
  image: 960048260646.dkr.ecr.us-west-2.amazonaws.com/helm-tester:latest
  only:
    - master
  script:
    - helm push ./nodelocal-dns-cache https://cordial-charts.dev.cordialdev.com
    - helm push ./nodelocal-dns-cache --username cordial --password $PROD_HELM_REPO_PASSWORD https://cordial-charts.us-west-1.cordial.io
